import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/function/Navbar';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/function/ThemeProvider';



const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let dark = false;

  return (
    <html lang="w-screen h-screen">
      <body
        className={cn(
          inter.className,
          'w-screen h-screen  bg-background text-foreground'
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* navbar */}
          <Navbar />
          
          {/* <Sidebar /> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
